version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: vocecaffe-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vocecaffe
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
    labels:
      com.docker.compose.project: "vocecaffe"
      com.docker.compose.service: "db"
      com.docker.compose.version: "1.29.2"
      com.docker.compose.config-hash: "1234567890abcdef"